SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM (
    SELECT MEMBER_ID, COUNT(*)
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
) AS BASE
JOIN MEMBER_PROFILE M ON BASE.MEMBER_ID = M.MEMBER_ID
JOIN REST_REVIEW R ON BASE.MEMBER_ID = R.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT
