WITH MAX_PRICES AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
)
SELECT F.CATEGORY, F.PRICE AS MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN MAX_PRICES M ON F.CATEGORY = M.CATEGORY
WHERE M.MAX_PRICE = F.PRICE
ORDER BY F.PRICE DESC